# Generated by Django 3.2.6 on 2023-04-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_main', models.CharField(blank=True, max_length=500, verbose_name='About sentence')),
                ('about_secondary', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('image', models.FileField(blank=True, upload_to='main')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('APP', 'APP'), ('CARD', 'CARD'), ('WEB', 'WEB'), ('BOT', 'BOT')], max_length=4)),
                ('image', models.FileField(blank=True, upload_to='portfolio')),
                ('name', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=50)),
                ('project_date', models.DateField(auto_now_add=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=100)),
                ('imag1', models.FileField(blank=True, null=True, upload_to='portfolio')),
                ('imag2', models.FileField(blank=True, null=True, upload_to='portfolio')),
                ('imag3', models.FileField(blank=True, null=True, upload_to='portfolio')),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.PositiveIntegerField()),
                ('projects', models.PositiveIntegerField()),
                ('hours_of_support', models.CharField(max_length=20)),
                ('hard_work', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your fullname', max_length=100, verbose_name='Full name')),
                ('position', models.CharField(max_length=50, verbose_name='Occupation')),
                ('position_en', models.CharField(max_length=50, null=True, verbose_name='Occupation')),
                ('position_uz', models.CharField(max_length=50, null=True, verbose_name='Occupation')),
                ('image', models.FileField(null=True, upload_to='teams')),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='Clien name')),
                ('position', models.CharField(max_length=40, verbose_name='Occupation')),
                ('advice', models.TextField(verbose_name='description')),
                ('image', models.FileField(blank=True, null=True, upload_to='clients')),
            ],
        ),
    ]
