# Generated by Django 3.2.6 on 2023-04-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_company',
            name='about_main',
            field=models.CharField(blank=True, help_text='About sentence', max_length=500),
        ),
        migrations.AlterField(
            model_name='about_company',
            name='about_secondary',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='about_company',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(help_text='Client name or organisation', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(help_text='Category name, Web design, Graphic', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(help_text='Ex: Web1, Web2, App1, Bot1, Card1', max_length=10),
        ),
        migrations.AlterField(
            model_name='teams',
            name='full_name',
            field=models.CharField(help_text='Enter your fullname', max_length=100),
        ),
        migrations.AlterField(
            model_name='teams',
            name='position',
            field=models.CharField(help_text='Occupation', max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='position_en',
            field=models.CharField(help_text='Occupation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='position_uz',
            field=models.CharField(help_text='Occupation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='advice',
            field=models.TextField(help_text='description'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='full_name',
            field=models.CharField(help_text='Clien name', max_length=40),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='position',
            field=models.CharField(help_text='Occupation', max_length=40),
        ),
    ]
