# Generated by Django 3.2.6 on 2023-04-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230408_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='desc_en',
            field=models.TextField(help_text='about project', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='desc_uz',
            field=models.TextField(help_text='about project', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name_en',
            field=models.CharField(help_text='Category name, Web design, Graphic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name_uz',
            field=models.CharField(help_text='Category name, Web design, Graphic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_title_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='advice_en',
            field=models.TextField(help_text='description', null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='advice_uz',
            field=models.TextField(help_text='description', null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='position_en',
            field=models.CharField(help_text='Occupation', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='position_uz',
            field=models.CharField(help_text='Occupation', max_length=40, null=True),
        ),
    ]
